name: Release
on:
  release:
    types:
      - created

jobs:
  # publish_on_linux:
  #   runs-on: ubuntu-latest
  #   steps:
  #   - uses: actions/checkout@v2
  #   - uses: actions/setup-node@master
  #     with:
  #       node-version: 14
  #   - name: install dependencies
  #     run: npm install
  #   - name: publish
  #     env:
  #       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  #     run: npm run publish

  # publish_on_mac:
  #   runs-on: macos-latest
  #   steps:
  #   - uses: actions/checkout@v2
  #   - uses: actions/setup-node@master
  #     with:
  #       node-version: 14
  #   - name: install dependencies
  #     run: npm install
  #   - name: publish
  #     env:
  #       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  #     run: npm run publish

  publish_on_win:
    # https://github.com/MadLittleMods/node-usb-detection/pull/165/files
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@master
        with:
          node-version: 14
      - name: Download Cert
        id: write_file
        uses: timheuer/base64-to-file@v1.1
        with:
          fileName: 'cert.pfx'
          fileDir: './packager/'
          encodedString: ${{ secrets.WIN_CERT_FILE_BASE64 }}
      #     - name: Add msbuild to PATH
      #       uses: microsoft/setup-msbuild@v1.1
      #     - name: Setup VisualStudio for node-gyp
      #       run: npm config set msvs_version 2022
      # FIXME: Install `npm@^8` (latest v8) once
      # https://github.com/actions/setup-node/issues/411#issuecomment-1025543081
      # is fixed.
      #
      # Even though we install a new version of node-gyp locally in
      # the project, the CI always seems to use the npm bundled version of
      # node-gyp. Even following the instructions from the docs, I could get it working
      # on all other platforms except for Windows and npm@6, see
      # - https://github.com/nodejs/node-gyp/blob/245cd5bbe4441d4f05e88f2fa20a86425419b6af/docs/Updating-npm-bundled-node-gyp.md
      # - https://github.com/nodejs/node-gyp/blob/245cd5bbe4441d4f05e88f2fa20a86425419b6af/docs/Force-npm-to-use-global-node-gyp.md
      - name: "Install npm@^8 to get a more up to date bundled node-gyp"
        run: npm install --global npm@8.3.1
      - name: install dependencies
        run: npm ci
      - name: publish          
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WIN_CERT_PASS: ${{ secrets.CERTIFICATE_PASS }}
          WIN_CERT_FILE: ${{ steps.write_file.outputs.filePath }}
        run: npm run publish
